# 1. Node.js 이미지를 가져와요
FROM node:16

# 2. 작업 디렉토리 설정
WORKDIR /app

# 3. package.json과 package-lock.json 복사
COPY package*.json ./

# 4. npm install
RUN npm install

# 5. 나머지 소스 복사
COPY . .

# 6. 서버가 들어올 포트 열기 (예: 3001번 포트)
EXPOSE 3001

# 7. 실행 명령어
CMD ["npm", "run", "start"]